
services:
  this-week-in-past:
    image: rouhim/this-week-in-past
    build:
      dockerfile: Containerfile
      context: .
    volumes:
      - ~/Pictures/:/resources:ro # should be read only
    ports:
      - "8080:8080"